//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class category
    {
        public category()
        {
            this.employee = new HashSet<employee>();
        }
    
        public int idCategory { get; set; }
        public string nameCategory { get; set; }
        public Nullable<decimal> salaryMax { get; set; }
        public Nullable<decimal> salaryMin { get; set; }
    
        public virtual ICollection<employee> employee { get; set; }
    }
}
