//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class company
    {
        public company()
        {
            this.employee = new HashSet<employee>();
        }
    
        public int idCopmany { get; set; }
        public string nameCompany { get; set; }
    
        public virtual ICollection<employee> employee { get; set; }
    }
}
