//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class CompanyManagementEntities : DbContext
    {
        public CompanyManagementEntities()
            : base("name=CompanyManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<category> category { get; set; }
        public DbSet<company> company { get; set; }
        public DbSet<employee> employee { get; set; }
        public DbSet<history> history { get; set; }
        public DbSet<user> user { get; set; }
    
        public virtual int Increase(Nullable<decimal> inc, Nullable<int> id)
        {
            var incParameter = inc.HasValue ?
                new ObjectParameter("inc", inc) :
                new ObjectParameter("inc", typeof(decimal));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Increase", incParameter, idParameter);
        }
    }
}
